import 'package:flutter/material.dart';

class AppProvider extends ChangeNotifier {
  String _language = 'pt';

  String get language => _language;

  void changeLanguage(String newLanguage) {
    _language = newLanguage;
    notifyListeners();
  }

  Map<String, Map<String, String>> get translations => {
    'pt': {
      'settings': 'Configurações',
      'appearance': 'Aparência',
      'appearance_desc': 'Personalize a interface do app',

      'security': 'Segurança',
      'security_desc': 'Configurações de segurança',
      'biometric_auth': 'Autenticação biométrica',
      'biometric_desc': 'Usar impressão digital ou Face ID',
      'change_password': 'Alterar senha',
      'change_password_desc': 'Modificar sua senha de acesso',
      'preferences': 'Preferências',
      'preferences_desc': 'Configurações gerais',
      'language': 'Idioma',
      'currency': 'Moeda',
      'about': 'Sobre',
      'about_desc': 'Informações do aplicativo',
      'terms': 'Termos de uso',
      'terms_desc': 'Leia os termos e condições',
      'privacy': 'Política de privacidade',
      'privacy_desc': 'Como tratamos seus dados',
      'version': 'Versão do app',
      'select_language': 'Selecionar Idioma',
      'select_currency': 'Selecionar Moeda',
      'currency_soon': 'Esta funcionalidade será implementada em breve.',
      'ok': 'OK',
      'current_password': 'Senha atual',
      'new_password': 'Nova senha',
      'confirm_password': 'Confirmar nova senha',
      'save': 'Salvar',
      'cancel': 'Cancelar',
      'password_changed': 'Senha alterada com sucesso!',
      'terms_title': 'Termos de Uso',
      'privacy_title': 'Política de Privacidade',
      'cart': 'Carrinho',
      'history': 'Histórico',
      'offers': 'Ofertas',
      'notifications': 'Notificações',
      'payments': 'Pagamentos',
      'profile': 'Perfil',
      'home': 'Início',
      'welcome_back': 'Bem-vindo\nde volta!',
      'login_subtitle': 'Entre com sua conta para continuar',
      'email': 'E-mail',
      'password': 'Senha',
      'forgot_password': 'Esqueceu a senha?',
      'login': 'Entrar',
      'or_continue': 'ou continue com',
      'no_account': 'Não tem uma conta? ',
      'register': 'Cadastre-se',
      'create_account': 'Criar\nConta',
      'register_subtitle': 'Preencha os dados para criar sua conta',
      'full_name': 'Nome completo',
      'confirm_password_field': 'Confirmar senha',
      'accept_terms': 'Li e aceito os termos de uso e a política de privacidade',
      'create_account_btn': 'Criar Conta',
      'already_have_account': 'Já tem uma conta? ',
      'login_here': 'Entre aqui',
    },
    'en': {
      'settings': 'Settings',
      'appearance': 'Appearance',
      'appearance_desc': 'Customize the app interface',

      'security': 'Security',
      'security_desc': 'Security settings',
      'biometric_auth': 'Biometric authentication',
      'biometric_desc': 'Use fingerprint or Face ID',
      'change_password': 'Change password',
      'change_password_desc': 'Modify your access password',
      'preferences': 'Preferences',
      'preferences_desc': 'General settings',
      'language': 'Language',
      'currency': 'Currency',
      'about': 'About',
      'about_desc': 'App information',
      'terms': 'Terms of use',
      'terms_desc': 'Read terms and conditions',
      'privacy': 'Privacy policy',
      'privacy_desc': 'How we handle your data',
      'version': 'App version',
      'select_language': 'Select Language',
      'select_currency': 'Select Currency',
      'currency_soon': 'This feature will be implemented soon.',
      'ok': 'OK',
      'current_password': 'Current password',
      'new_password': 'New password',
      'confirm_password': 'Confirm new password',
      'save': 'Save',
      'cancel': 'Cancel',
      'password_changed': 'Password changed successfully!',
      'terms_title': 'Terms of Use',
      'privacy_title': 'Privacy Policy',
      'cart': 'Cart',
      'history': 'History',
      'offers': 'Offers',
      'notifications': 'Notifications',
      'payments': 'Payments',
      'profile': 'Profile',
      'home': 'Home',
      'welcome_back': 'Welcome\nback!',
      'login_subtitle': 'Sign in to your account to continue',
      'email': 'Email',
      'password': 'Password',
      'forgot_password': 'Forgot password?',
      'login': 'Sign In',
      'or_continue': 'or continue with',
      'no_account': 'Don\'t have an account? ',
      'register': 'Sign up',
      'create_account': 'Create\nAccount',
      'register_subtitle': 'Fill in the details to create your account',
      'full_name': 'Full name',
      'confirm_password_field': 'Confirm password',
      'accept_terms': 'I have read and accept the terms of use and privacy policy',
      'create_account_btn': 'Create Account',
      'already_have_account': 'Already have an account? ',
      'login_here': 'Sign in here',
    },
    'es': {
      'settings': 'Configuración',
      'appearance': 'Apariencia',
      'appearance_desc': 'Personaliza la interfaz de la app',

      'security': 'Seguridad',
      'security_desc': 'Configuración de seguridad',
      'biometric_auth': 'Autenticación biométrica',
      'biometric_desc': 'Usar huella digital o Face ID',
      'change_password': 'Cambiar contraseña',
      'change_password_desc': 'Modificar tu contraseña de acceso',
      'preferences': 'Preferencias',
      'preferences_desc': 'Configuración general',
      'language': 'Idioma',
      'currency': 'Moneda',
      'about': 'Acerca de',
      'about_desc': 'Información de la aplicación',
      'terms': 'Términos de uso',
      'terms_desc': 'Lee los términos y condiciones',
      'privacy': 'Política de privacidad',
      'privacy_desc': 'Cómo tratamos tus datos',
      'version': 'Versión de la app',
      'select_language': 'Seleccionar Idioma',
      'select_currency': 'Seleccionar Moneda',
      'currency_soon': 'Esta funcionalidad será implementada pronto.',
      'ok': 'OK',
      'current_password': 'Contraseña actual',
      'new_password': 'Nueva contraseña',
      'confirm_password': 'Confirmar nueva contraseña',
      'save': 'Guardar',
      'cancel': 'Cancelar',
      'password_changed': '¡Contraseña cambiada exitosamente!',
      'terms_title': 'Términos de Uso',
      'privacy_title': 'Política de Privacidad',
      'cart': 'Carrito',
      'history': 'Historial',
      'offers': 'Ofertas',
      'notifications': 'Notificaciones',
      'payments': 'Pagos',
      'profile': 'Perfil',
      'home': 'Inicio',
      'welcome_back': 'Bienvenido\nde vuelta!',
      'login_subtitle': 'Inicia sesión en tu cuenta para continuar',
      'email': 'Correo electrónico',
      'password': 'Contraseña',
      'forgot_password': '¿Olvidaste la contraseña?',
      'login': 'Iniciar Sesión',
      'or_continue': 'o continúa con',
      'no_account': '¿No tienes una cuenta? ',
      'register': 'Regístrate',
      'create_account': 'Crear\nCuenta',
      'register_subtitle': 'Completa los datos para crear tu cuenta',
      'full_name': 'Nombre completo',
      'confirm_password_field': 'Confirmar contraseña',
      'accept_terms': 'He leído y acepto los términos de uso y la política de privacidad',
      'create_account_btn': 'Crear Cuenta',
      'already_have_account': '¿Ya tienes una cuenta? ',
      'login_here': 'Inicia sesión aquí',
    },
  };

  String translate(String key) {
    return translations[_language]?[key] ?? key;
  }
}