name: tcc
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.1
  google_fonts: ^6.1.0
  flutter_animate: ^4.2.0+1
  font_awesome_flutter: ^9.2.0
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/images/tcc.png